services:
  go-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: go-img:latest
    container_name: go-container
    ports:
      - 80:8080 # localport:dockerport
    volumes:
      - ./:/app
